from django.db import models
from django.contrib.auth.models import User

import secrets
import datetime
# Create your models here.

class UserResetPassword(models.Model):
    '''
    This model is for reset password. The database table contains five columns:
    id: Autogenerated
    user: ForeignKey from User Model
    token: String generate when request a password reset
    date: A DateTimeField for token validation
    is_valid: A BooleanField for valid token reset password
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now=True)
    is_valid = models.BooleanField(default=True)

    def generate_token(self):
        return secrets.token_urlsafe()

    def check_token(self, token):
        '''
        Check token validity for an hour since was generated.
        '''
        tz = self.date.tzinfo
        t_now = datetime.datetime.now(tz=tz)

        # Check the token time less than hour
        dt = t_now - self.date
        if dt.total_seconds() > 3600:
            self.is_valid = False

        # Return True if the token is correct and is_valid
        res = (token == self.token) and self.is_valid
        
        # Set the token invalid
        self.is_valid = False

        return res

    def save(self, *args, **kwargs):
        '''
        Until save generate a new token and set valid.
        '''
        # Generate a token and set valid
        self.token = self.generate_token()
        self.is_valid = True
        super(UserResetPassword, self).save(*args, **kwargs)

