# Generated by Django 3.0.4 on 2020-05-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
