# Generated by Django 3.0.4 on 2020-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Processing'), (2, 'Preparing'), (3, 'Delivering'), (4, 'Ready')], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='additional',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_unitary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
