# Generated by Django 3.0.4 on 2020-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20200511_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'Preparing'), ('3', 'Delivering'), ('4', 'Ready')], default='1', max_length=15),
        ),
    ]
