# Generated by Django 3.0.4 on 2020-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_auto_20200512_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default='s1', max_length=200),
            preserve_default=False,
        ),
    ]
