# Generated by Django 3.0.4 on 2020-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(max_length=80),
        ),
    ]
