# Generated by Django 3.0.4 on 2020-04-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30, unique=True, verbose_name='Menu Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(max_length=20, unique=True, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=30, verbose_name='Topping')),
                ('price', models.FloatField(default=0.0)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ProductSize')),
                ('topping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('product_description', models.TextField(blank=True, max_length=400, verbose_name='Description')),
                ('product_price', models.FloatField(default=0.0, verbose_name='Price')),
                ('product_additional', models.ManyToManyField(blank=True, related_name='additional', to='orders.Topping')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size', to='orders.ProductSize')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_type', to='orders.MenuItem')),
            ],
        ),
    ]
