# Generated by Django 3.0.4 on 2020-04-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200419_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=20, unique=True, verbose_name='Variation')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ProductVariation'),
        ),
    ]
