# Generated by Django 3.0.4 on 2020-04-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200420_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='item_type',
            field=models.ManyToManyField(related_name='menu_type', to='orders.MenuItem'),
        ),
    ]
