# Generated by Django 3.0.4 on 2020-04-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productsize_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ProductSize'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='item_type',
            field=models.ManyToManyField(related_name='sizes', to='orders.MenuItem'),
        ),
    ]
