# Generated by Django 3.0.4 on 2020-05-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200425_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restaurant')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Phone Number')),
                ('image', models.ImageField(upload_to='owner')),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='type_variation',
            field=models.CharField(choices=[('B', 'base'), ('P', 'predefined'), ('U', 'user defined')], default='B', max_length=20),
        ),
    ]
