# Generated by Django 3.0.4 on 2020-05-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200504_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
