# Generated by Django 3.0.4 on 2020-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_add',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='type_variation',
            field=models.CharField(default='base', max_length=20),
        ),
        migrations.DeleteModel(
            name='PriceToppingList',
        ),
    ]
