# Generated by Django 3.0.4 on 2020-06-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_openhours_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='schedule',
            field=models.ManyToManyField(to='orders.Schedule'),
        ),
    ]
