# Generated by Django 3.0.4 on 2020-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_place_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='hour_form',
            new_name='hour_from',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1),
        ),
    ]
