# Generated by Django 3.0.4 on 2020-06-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200608_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_from',
            field=models.ManyToManyField(to='orders.OpenHours'),
        ),
    ]
