# Generated by Django 3.0.4 on 2020-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200608_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_from',
            field=models.ManyToManyField(related_name='_schedule_hour_from_+', to='orders.OpenHours'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour_to',
            field=models.ManyToManyField(related_name='_schedule_hour_to_+', to='orders.OpenHours'),
        ),
    ]
