# Generated by Django 3.0.4 on 2020-06-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200608_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hour_to',
        ),
    ]
