# Generated by Django 3.0.4 on 2020-06-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_schedule_hour_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_from',
            field=models.ManyToManyField(related_name='hourfrom', to='orders.OpenHours'),
        ),
    ]
