# Generated by Django 3.0.4 on 2020-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200608_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hour_from',
        ),
        migrations.AddField(
            model_name='schedule',
            name='horita',
            field=models.ManyToManyField(related_name='hour', to='orders.OpenHours'),
        ),
    ]
