# Generated by Django 3.0.4 on 2020-06-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200608_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='horita',
        ),
        migrations.AddField(
            model_name='schedule',
            name='horita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.OpenHours'),
            preserve_default=False,
        ),
    ]
