# Generated by Django 3.0.4 on 2020-06-08 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200608_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='horita',
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hourfrom', to='orders.OpenHours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hourto', to='orders.OpenHours'),
            preserve_default=False,
        ),
    ]
